### ISSUE TITLE
是否需要添加provider？直接使用没有办法找services配置项

### ISSUE THREAD

**Issue by caingougou** [medz/laravel-jpush-notification-channel#1]
是否需要添加provider？直接使用没有办法找services配置项

**Comment by medz** [comment]
我测试了可以直接找到呢。你的 laravel 版本是？需要有“自动发现”功能的 laravel 版本。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2019年4月15日，00:33，caingougou <notifications@github.com<mailto:notifications@github.com>> 写道：


是否需要添加provider？直接使用没有办法找services配置项
