### ISSUE TITLE
Ios 推送需要设置标题，setNotification 报错

### ISSUE THREAD

**Issue by king-fang** [medz/laravel-jpush-notification-channel#3]
![image](https://user-images.githubusercontent.com/29619744/70217163-95364700-177b-11ea-9c65-bdcdfc1264d4.png)

**Comment by medz** [comment]
收到！我测试一下！

**Comment by king-fang** [comment]
@medz 哈哈，貌似是类型提示错误的问题，还有希望将推送的结果返回！

**Comment by medz** [comment]
好的，我主要是没测试出来～可能我按照文档设置的太标准了。我把异常抛出吧！这样外层用的时候接收异常就可以了

**Comment by medz** [comment]
目前我是屏蔽了异常的

**Comment by medz** [comment]
你好，更新了，请使用 1.0.2 版本，该版本修复了不能设置 alert 为数组详情问题和解放第三方异常抛出。
