### ISSUE TITLE
怎么触发通知呢？  Notification::send ？

### ISSUE THREAD

**Issue by chenchenchen95** [medz/laravel-jpush-notification-channel#5]
我的触发通知是用的
            $course_sub = CourseSubModel::query()->first();
            Notification::send($course_sub, new CourseSure());

在CouserSubModel添加了

    protected function routeNotificationForJpush()
    {
        return new JPushSender([
            'platform' => 'all',
            'audience' => [
                'alias' => sprintf('user_%d', $this->id),
            ],
        ]);
    }

但还是报错
  #message: "Call to undefined method App\Model\Course\CourseSubModel::routeNotificationFor()"
  #code: 0
  #file: "/www/wwwroot/api.shenyanshe.95shouyou.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php"

该怎么正确触发通知呢？

**Comment by medz** [comment]
https://learnku.com/docs/laravel/7.x/notifications/7489#sending-notifications 这个只是 Laravel Notification 的一个驱动，自身不具备发送通知的触发功能。触发应当使用 Laravel notifiaction 的方式触发。

**Comment by medz** [comment]
从你上面的代码可以看出，你的 `CourseSubModel ` 模型没有添加 `use Illuminate\Notifications\Notifiable` 所以 laravel notification 无法识别任何驱动。

这个性状是默认 User 模型添加了的，其他模型要使用需要给对应的 model 添加 `use Illuminate\Notifications\Notifiable ` 代码

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/81816621-2e089400-955e-11ea-851f-d60cad3c7b8c.png)
![image](https://user-images.githubusercontent.com/5564821/81816655-3c56b000-955e-11ea-9a75-22adff6d31ee.png)
laravel 文档中依旧明确说明了哦
